### ISSUE TITLE
deep nesting

### ISSUE THREAD

**Issue by sonhanguyen** [LockedOn/tiny-duck#2]
I believe I have found a bug. If you nest deeper than 2 levels, like this

``` javascript
TinyDuck({
    child: TinyDuck({
        grandChild: TinyDuck({
            handler() {}
        })
    })
})
```

... you will hit `Uncaught TypeError: act.substring is not a function` at [line 77](http://github.com/LockedOn/tiny-duck/blob/c233cccbb087c3e25b2120fd8bfb7cea01983d1e/src/index.js#L77)
A quick fix to shut that console error:

``` javascript
       // Add parent namespace where not an abosolute action
       const newNs = (act) => {
+         if (typeof act != 'string') return Object.keys(act).reduce(
+            (obj, key) => ({...obj, [key]: newNs(act[key])})
+         , {})
          if (act.substring(0, 1) === "/") {
```

although I'm not sure if there is anything else I've missed.

**Comment by karlmikko** [comment]
Thanks @sonhanguyen I can reproduce the problem. I also understand the cause.

To re-namespace the actions and reducers are different. As the reducer tree is flat and the actions tree is deeply nested.

Great bug find!
