### ISSUE TITLE
I have implemented an NPM library named ducks; trying to solve the smiliar problem as this project

### ISSUE THREAD

**Issue by huan** [LockedOn/tiny-duck#4]
Hello @karlmikko ,

I'm the creator of [Ducks](https://github.com/huan/ducks), which is a Reducer Bundles Manager that Implements the Redux Ducks Modular Proposal with Great Convenience.

I'd like to invite you to have a look at it, and any feedbacks are welcome.

Thank you very much!

Link to:

- https://github.com/huan/ducks/issues/7

**Comment by karlmikko** [comment]
@huan cool! I have not done much with tiny-duck for a few years, though we still use this in an internal project at LockedOn. So I am not sure I would be much help as way of feedback as this problem space is not really in my head anymore.

**Comment by huan** [comment]
It's great to get your reply, and I hope you have a great Lunar New Year!
